### ISSUE TITLE
Twitter scraping failing

### ISSUE THREAD

**Issue by sibeshkar** [mayahq/maya-red-browser-automation#11]
Query shows successfully scraped even when page hasn't loaded. Doesn't show element not found error.

[flows.txt](https://github.com/mayahq/maya-red-browser-automation/files/6545369/flows.txt)

**Comment by dusnat** [comment]
WebQL does not error out when xpaths are not found, it simply populates null values for those xpaths. 

This could be because the tweets are loaded into DOM after the page loads. The `open` and `update-page` nodes return a response only when the browser has confirmed that the page has finished loading, but if a page depends on javascript too much it'll respond before the DOM elements are _actually_ loaded.

**Comment by sibeshkar** [comment]
Turns out that adding a delay node fixes this
